run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: (_test\.go|test/)
      linters:
        - dupl
        - goconst
        - unparam
        - errcheck
    - text: "unused-parameter"
      path: _test\.go
      linters:
        - revive
